Automatically scrolls to current day in timetable
shymmq/librus-client-kotlin pull request #36
Opened 2017-10-01 20:46 UTC by asdfMaciej

2017-10-01 21:03 UTC, shymmq requested changes

2017-10-01 21:03 UTC, shymmq commented on app/src/main/java/com/wabadaba/dziennik/ui/timetable/TimetableFragment.kt
> +                val days_n = mutableListOf<Int>()
Create current date here as LocalDate.now()

2017-10-01 21:03 UTC, shymmq commented on app/src/main/java/com/wabadaba/dziennik/ui/timetable/TimetableFragment.kt
> +                    days_n.add(current_n)
Compare date to today's date if they equal, save the header element

2017-10-01 21:03 UTC, shymmq commented on app/src/main/java/com/wabadaba/dziennik/ui/timetable/TimetableFragment.kt
> +                adapter!!.recyclerView!!.scrollToPosition(days_n.get(day))
scroll to todays header element if exists instead of index

2017-10-01 21:11 UTC, asdfMaciej commented
Alright, will fix in spare time (probably tomorrow)

2017-10-02 15:31 UTC, asdfMaciej commented
I've addressed to the changes

2017-10-18 21:17 UTC, rowysock requested changes

2017-10-18 21:17 UTC, rowysock commented on app/src/main/java/com/wabadaba/dziennik/ui/timetable/TimetableFragment.kt
> +                    val c = Calendar.getInstance()
Please don't use old Java calendars. Use Joda instead. You got already prepared LocalDate date here

2017-10-18 21:17 UTC, rowysock commented on app/src/main/java/com/wabadaba/dziennik/ui/timetable/TimetableFragment.kt
> +                val today_day = Calendar.getInstance().get(Calendar.DAY_OF_WEEK)
Make it Joda LocalDate
Also in Java camelCase is preffered over underscore_case

2017-10-18 21:17 UTC, rowysock commented on app/src/main/java/com/wabadaba/dziennik/ui/timetable/TimetableFragment.kt
> +                var _n = 0  // increases with every element
No need for this counter. scrollToPosition accepts both indices and elements

2017-12-20 20:53 UTC, closed without merging